// Export all calculator functions
export { calculateMortgage } from './mortgage'
export { calculateLoan } from './loan'
export { calculateCompoundInterest } from './compound-interest'
export { calculateCarLoan } from './car-loan'
export { calculateRetirement } from './retirement'
export { calculateCreditCardPayoff } from './credit-card'
export { calculateInvestment } from './investment'
export { calculateDebtPayoff } from './debt-payoff'
export { calculateSavingsGoal } from './savings-goal'
export { calculateStudentLoan } from './student-loan'
export { calculateAmortization } from './amortization'
export { calculateRentVsBuy } from './rent-vs-buy'
export { calculateNetWorth } from './net-worth'
export { calculateBudget } from './budget'
export { calculateInflation } from './inflation'
export { calculateSimpleInterest } from './simple-interest'
export { calculateHomeAffordability } from './home-affordability'
export { calculateRefinance } from './refinance'
export { calculateEmergencyFund } from './emergency-fund'
export { calculateSalary } from './salary'

// Export types
export type { MortgageInputs, MortgageResults, AmortizationRow } from './mortgage'
export type { LoanInputs, LoanResults } from './loan'
export type { CompoundInterestInputs, CompoundInterestResults } from './compound-interest'
export type { CarLoanInputs, CarLoanResults } from './car-loan'
export type { RetirementInputs, RetirementResults } from './retirement'
export type { CreditCardInputs, CreditCardResults } from './credit-card'
export type { InvestmentInputs, InvestmentResults } from './investment'
export type { DebtPayoffInputs, DebtPayoffResults } from './debt-payoff'
export type { SavingsGoalInputs, SavingsGoalResults } from './savings-goal'
export type { StudentLoanInputs, StudentLoanResults } from './student-loan'
export type { AmortizationInputs, AmortizationResults } from './amortization'
export type { RentVsBuyInputs, RentVsBuyResults } from './rent-vs-buy'
export type { NetWorthInputs, NetWorthResults } from './net-worth'
export type { BudgetInputs, BudgetResults } from './budget'
export type { InflationInputs, InflationResults } from './inflation'
export type { SimpleInterestInputs, SimpleInterestResults } from './simple-interest'
export type { HomeAffordabilityInputs, HomeAffordabilityResults } from './home-affordability'
export type { RefinanceInputs, RefinanceResults } from './refinance'
export type { EmergencyFundInputs, EmergencyFundResults } from './emergency-fund'
export type { SalaryInputs, SalaryResults } from './salary'
